version: '3.7'
services:
  api:
    image: mattrayner/lamp:0.8.0-1804-php8
    container_name: api
    expose:
      - "80"
    ports:
      - "8000:80"
    volumes:
      - .:/app
    network_mode: bridge
